package com.ibrahim.camelan_task.base

const val CLIENT_ID = "OUWRAHTWSAVSBBAOKP0AAOETGY2AAX4OJ5IAQW2HBIS1K25U"
const val CLIENT_SECRET = "4MQ4QVKXSINPFVNAMHIDT5POTRBOTIOFSPHQK5ER3IPX1BBF"
const val BASE_URL = "https://api.foursquare.com/v2/venues/"
const val API_VERSION = "20210517"





//const val CLIENT_ID = "1GQUSH4IY3RZ1RNF0XBCWYENSAM41BVLDJCNWKH2HXEJJVK4"
//const val CLIENT_SECRET = "N33CQGNB2OPKO2143OVCSJVKMWTNELAA2ZFQIW5KVAU4IAXE"

